name: enough_coi
description: Experimental client for COI apps. [COI](https://coi-dev.org) is a server and client standard  for messaging based on email.
version: 0.0.4
homepage: https://github.com/Enough-Software/enough_coi

environment:
  sdk: '>=2.7.0 <3.0.0'
  
dependencies:
  basic_utils: ^2.4.7
  xml: ^3.7.0
  event_bus: ^1.1.0
  objectdb: ^1.0.7+1
  json_annotation: ^3.0.1
  enough_mail: ^0.0.3
    #path: ../enough_mail
  uuid: ^2.0.4

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
  build_runner: ^1.7.3
  json_serializable: ^3.2.5
